# Generated by Django 5.0 on 2024-06-20 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_orderlist'),
        ('storesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('products', models.ManyToManyField(related_name='wishlists', to='storesapp.productmodel')),
            ],
        ),
    ]
