# Generated by Django 5.0 on 2024-06-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_wishlist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
