# Generated by Django 5.0 on 2024-06-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='c_phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
