# Generated by Django 5.0 on 2024-06-25 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_remove_confirmorder_productname_confirmorder_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmorder',
            name='final',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.finalorder'),
            preserve_default=False,
        ),
    ]
