# Generated by Django 5.0 on 2024-06-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_remove_finalorder_finaltotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='subtotal',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
