# Generated by Django 5.0 on 2024-06-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_finalorder_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalorder',
            old_name='subtotal',
            new_name='finaltotal',
        ),
    ]
