# Generated by Django 5.0 on 2024-06-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_rename_subtotal_finalorder_finaltotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalorder',
            old_name='total',
            new_name='subtotal',
        ),
    ]
