# Generated by Django 5.0 on 2024-06-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_rename_total_finalorder_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalorder',
            old_name='subtotal',
            new_name='total',
        ),
    ]
