# Generated by Django 5.0 on 2024-06-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_rename_subtotal_finalorder_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalorder',
            name='total',
        ),
    ]
