# Generated by Django 5.0 on 2024-06-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_remove_finalorder_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalorder',
            old_name='finaltotal',
            new_name='total',
        ),
    ]
