# Generated by Django 5.0 on 2024-06-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_rename_finaltotal_finalorder_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='finaltotal',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
