# Generated by Django 5.0 on 2024-06-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storesapp', '0002_delete_listmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='c_phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='s_phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
