# Generated by Django 5.0 on 2024-06-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storesapp', '0003_alter_invoice_c_phone_alter_storemodel_s_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='s_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='s_phone',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='store_name',
        ),
    ]
