# Generated by Django 5.0 on 2024-06-21 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storesapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='listmodel',
        ),
    ]
