# Generated by Django 5.0 on 2024-06-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storesapp', '0004_remove_invoice_s_address_remove_invoice_s_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='invoice',
            new_name='productinvoice',
        ),
    ]
