# Generated by Django 5.0 on 2024-06-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storesapp', '0005_rename_invoice_productinvoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productinvoice',
        ),
    ]
